### ISSUE TITLE
在Obsidian中可以正常显示的html table Sync至Notion后没有过来

### ISSUE THREAD

**Issue by wyih** [EasyChris/obsidian-to-notion#16]
「Huxtable.md」https://www.aliyundrive.com/s/7vNB3d9njTg 提取码: 9lm9

MD如上所示，有没有什么好办法可以保留这些table，这些table是我直接用Rmarkdown生成的。

**Comment by EasyChris** [comment]
> 「Huxtable.md」https://www.aliyundrive.com/s/7vNB3d9njTg 提取码: 9lm9
> 
> MD如上所示，有没有什么好办法可以保留这些table，这些table是我直接用Rmarkdown生成的。

应该是格式notion不支持。。暂时没啥好办法

**Comment by wyih** [comment]
我看到有一个办法是将这样的代码转成embedded URL，解决方案如下：https://apption.co/apps/63
但一张一张表复制粘贴太累了，有办法可以自动化这个流程吗？

**Comment by wyih** [comment]
> 

感觉好像没有折腾的意义，太依赖于apption.co了

**Comment by EasyChris** [comment]
> > 
> 
> 感觉好像没有折腾的意义，太依赖于apption.co了

这个可能需要你自己解决一下，可以试试写一个脚本。因为普通的table是没有啥问题的。

插件暂时只支持普通的md语法。
