### ISSUE TITLE
Network error Error Issue

### ISSUE THREAD

**Issue by elf7979** [EasyChris/obsidian-to-notion#17]
status code is 400

I think I precisely followed the guidance.
Any idea why network error is occuring?

**Comment by EasyChris** [comment]
Can you post a screenshot of the error?

**Comment by elf7979** [comment]
Yes.
This is the screenshot.
![obsidian_notion_failure mov](https://user-images.githubusercontent.com/15778931/181445262-50136dd0-2008-474f-8c48-4425ef11715b.gif)

**Comment by EasyChris** [comment]
plz double check notion token and databaseID is right 

and check database first custom name must be "Name", otherwise sync to notion will be failed

**Comment by elf7979** [comment]
It works now. Thanks a lot. I thought I changed the first column as "Name" but it wasn't.

But my process went this way:
1) changed the column name to "Name"
2) I double checked my Notion API and databaseID and recopied and repasted
3) I wasn't sure whether the API and dbID put in correctly since there was no button to submit in plugin UI
4) I uninstalled plugin and reinstalled plugin and put the API and databaseID again
5) It worked

Thanks for the wonderful plugin

**Comment by EasyChris** [comment]
> I wasn't sure whether the API and dbID put in correctly since there was no button to submit in plugin UI

when you paste database id or notion api. it will auto save

maybe i should change the password type to input that you can see the databaseID and notion api

**Comment by LittleHaku** [comment]
Did everything here and didn't work

**Comment by ho2sky-Git** [comment]
help me....  i do not know thw why ...
![image](https://user-images.githubusercontent.com/96983554/223022377-63c09a00-174d-44fa-a899-ad4da6776d4f.png)

why Network error 400 ???

**Comment by patyiscoding** [comment]
Platform: MacOS

Having the same problem here even though my `Notion API key` and `database ID` are correct and I have a `Name` column in my table.

If it helps, this is the possible cause of the Network error 400 that shows up in the console:

`plugin:obsidian-to-notion:15432 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'status')
    at Upload2Notion.eval (plugin:obsidian-to-notion:15432:15)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-to-notion:53:24)
e`

**Comment by aideward** [comment]
Does anyone have a fix for this
