### ISSUE TITLE
报400网络错误

### ISSUE THREAD

**Issue by zhanyonghua** [EasyChris/obsidian-to-notion#19]
可以确信网络没问题,notion可以正常使用，OB上点share to notion时报：网络错，请求失败，状态400

**Comment by EasyChris** [comment]
请再次仔细阅读确认tokenid 和 databaseid 没有错误。

database第一个字段为 name 而不是 名字

**Comment by EasyChris** [comment]
https://github.com/EasyChris/obsidian-to-notion/blob/master/README-zh.md

**Comment by zhanyonghua** [comment]
确实是第一个字段名称问题。
如果能把ob中以“：”来识别字段，再插到到表格对应名称的列中，就更赞了！！！

**Comment by EasyChris** [comment]
后续可能会考虑这个feature
