### ISSUE TITLE
[Feature Request] - Sync Images also

### ISSUE THREAD

**Issue by HarshIceHummer** [EasyChris/obsidian-to-notion#26]
I'd like to have the option of keeping offline images in Obsidian and online images in Notion.

**Comment by EasyChris** [comment]
Use the [image auto upload plugin](https://github.com/renmu123/obsidian-image-auto-upload-plugin) to upload the image to the corresponding cloud storage.

this plugin when you paste img, will auto upload img to cloud. when you upload this md file to notion, the img url will auto upload to notion

**Comment by HarshIceHummer** [comment]
I wanted to keep the images offline in Obsidian, so that I could edit them
in future if need be.
