### ISSUE TITLE
network error Error:Request failed,status 404

### ISSUE THREAD

**Issue by Raviney** [EasyChris/obsidian-to-notion#28]
![image](https://user-images.githubusercontent.com/70245794/191783542-e4f69040-65cb-4e4e-b239-fe125f36edb5.png)
I refer to #17 and recheck it many times but don't work.

**Comment by LittleHaku** [comment]
same

**Comment by EasyChris** [comment]
plz check notion api token and databaseID is correct

and check [database share to web] is true

<img width="461" alt="image" src="https://user-images.githubusercontent.com/9960087/194557599-a36efb6b-41ce-4332-9144-7c7e27fe740e.png">

**Comment by EasyChris** [comment]
merge to #24
