### ISSUE TITLE
当图床图片的链接前带有List标记时，notion中图片无法显示

### ISSUE THREAD

**Issue by MaxLEAF3824** [EasyChris/obsidian-to-notion#29]
首先感谢作者提供这么一个架起notion和obsidian的桥梁

- markdown中这么写时：
  - `![test](https://tuchuang.net/test.png)`
  - notion中的图片可以正常显示
- markdown中这么写时：
  - `- ![test](https://tuchuang.net/test.png)`
  - notion中图片无法显示

初步定位为markdown2block的问题，这个BUG能修嘛

**Comment by EasyChris** [comment]
应该是notion不支持 `- ![test](https://tuchuang.net/test.png)` 这种写法 

大部分写img markdown还是使用  `![test](https://tuchuang.net/test.png)`  这种写法

这个应该不算bug，算一个兼容性问题吧。可以加一个正则过滤。

我有点奇怪，为什么会使用 `- ![test](https://tuchuang.net/test.png)` 这种写法呢？

**Comment by MaxLEAF3824** [comment]
还有希望能多记录一些上传失败报错信息，只有一个status400真的很难搞...

**Comment by EasyChris** [comment]
正常的token这些错误会有报告，一些未知的错误，只有一个400，后续会改进，感谢报告
