### ISSUE TITLE
对于多行的行间公式，上传至notion后会自动添加换行

### ISSUE THREAD

**Issue by hrtdream** [EasyChris/obsidian-to-notion#33]
![CleanShot 2022-12-16 at 15 13 27@2x](https://user-images.githubusercontent.com/54263732/208043644-ff98018e-debb-4f35-bcc3-7b8e13efbb9b.png)

左侧为通过插件上传到Notion，右侧为Obsidian；对于多行的行间公式，上传后会自动添加双反斜线"\\\\"换行

**Comment by EasyChris** [comment]
建议向上游 提一个 建议issues https://github.com/tryfabric/martian
