### ISSUE TITLE
點擊plug-in沒有反應、也沒有出現錯誤訊息

### ISSUE THREAD

**Issue by gachua123** [EasyChris/obsidian-to-notion#37]
您好~ 
閱讀過readme文件多次，重新安裝多次，點擊plug-in沒有反應、也沒有出現錯誤訊息：
1. 確認過BRAT為最新版本
![image](https://user-images.githubusercontent.com/113978480/210032741-f07c4323-cde1-4ee1-b905-d46f82795fd7.png)

2. 確認過Notion 權限沒問題 (金鑰&ID也無誤，透過其他程式確認啟動無誤)，頁面也開啟公開權限，欄位名稱為Name預設值(英文介面)

3. 將資料夾自儲存處自雲端改為本地文件開啟後，仍點擊plug-in圖標仍然沒有反應，請教可能是哪裡出現錯誤呢??

**Comment by EasyChris** [comment]
你好，可否直接在插件中心下载尝试？

下载成功之后，请在插件中启动即可

**Comment by visiLi** [comment]
我的也是 这种问题 尝试好多方法 都不行 确定api和ID 没问题！数据库也授权了。没任何反应！

**Comment by visiLi** [comment]
> 我的也是 这种问题 尝试好多方法 都不行 确定api和ID 没问题！数据库也授权了。没任何反应！

使用的是从OB 第三方插件商店下载启用的
重新制作了【集合】、重新新建了页面和数据库！第一列名称也是【Name】。也授权了集合给数据库。
使用了集合的令牌！使用了数据库的ID。尝试了好几遍  均不成功！没有任何提示

**Comment by EasyChris** [comment]
@visiLi @gachua123 推送了最新一版本的 v0.7.6版本，请更新到最新版本，如果还有问题请在这里提出。

感谢反馈到bug，已经修复，祝新年快乐～

**Comment by visiLi** [comment]
> @visiLi @gachua123 推送了最新一版本的 v0.7.6版本，请更新到最新版本，如果还有问题请在这里提出。
> 
> 感谢反馈到bug，已经修复，祝新年快乐～

也祝亲 新年快乐！现在可以了，但。不是每次都能成功！对有图文和层级关系比较多的就没有任何反应！

**Comment by EasyChris** [comment]
> > @visiLi @gachua123 推送了最新一版本的 v0.7.6版本，请更新到最新版本，如果还有问题请在这里提出。
> > 感谢反馈到bug，已经修复，祝新年快乐～
> 
> 也祝亲 新年快乐！现在可以了，但。不是每次都能成功！对有图文和层级关系比较多的就没有任何反应！

如果方便的话，可以提供一下失败的md文件么？我可以复现看一下错误

**Comment by visiLi** [comment]
> 

@EasyChris 好得
[Obsidian 8 个进阶用法  全网最细图文详解.md](https://github.com/EasyChris/obsidian-to-notion/files/10328439/Obsidian.8.md)

**Comment by visiLi** [comment]
就是这个 点击没有反应！

**Comment by EasyChris** [comment]
> 就是这个 点击没有反应！

我测试是正常上传的，你等久一点看看，如果文件较大，上传到notion是需要大概等1～2s

等待的过程不要在点，或者这里我可以做一个上传loading的状态

**Comment by visiLi** [comment]
> > 就是这个 点击没有反应！
> 
> 我测试是正常上传的，你等久一点看看，如果文件较大，上传到notion是需要大概等1～2s
> 
> 等待的过程不要在点，或者这里我可以做一个上传loading的状态

报错：network error Error:Request failed, status400
![image](https://user-images.githubusercontent.com/42717403/210163410-20dc3b19-163f-4f0b-96e1-776bda42a8da.png)

**Comment by EasyChris** [comment]
这可能是notion的api网络原因，如果在国内，建议fq试试。。。
